cmake_minimum_required(VERSION 3.28)

project(lu_postgres CXX C)

set(CMAKE_CXX_STANDARD 23)
set(CMAKE_VS_INCLUDE_INSTALL_TO_DEFAULT_BUILD 1)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(CMAKE_INSTALL_PREFIX ${CMAKE_SOURCE_DIR}/bin)
set(CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake)
set(CPACK_MODULE_PATH ${CMAKE_MODULE_PATH}/templates)

set(CMAKE_INSTALL_RPATH "$ORIGIN")
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)

find_package(libpqxx CONFIG REQUIRED)

add_subdirectory(lu_postgres)
